version: '{build}'

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts/*
- path: 'src/**/bin/*'

test: off